version: "3.5"

services:
  vehicle-api:
    image: chathurangasandun/accoon.pitstop.apigateway:latest
    ports:
      - '5000:5000'
    networks:
      - pitstop

  customer-api:
    image: chathurangasandun/accoon.pitstop.customermanagement:latest
    ports:
      - '5001:5000'
    networks:
      - pitstop

  vehicle-api:
    image: chathurangasandun/accoon.pitstop.vehiclemanagement:latest
    ports:
      - '5002:5000'
    networks:
      - pitstop


networks:
  pitstop:
    name: pitstop-network
    external: true