version: "2"

services:
  customer-api:
    image: chathurangasandun/accoon.pitstop.customermanagement:latest
    ports:
      - '5001:5000'
    networks:
      - pitstop

  vehicle-api:
    image: chathurangasandun/accoon.pitstop.vehiclemanagement:latest
    ports:
      - '5002:5000'
    networks:
      - pitstop

networks:
  pitstop:
    name: pitstop-network